org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.daemon=false
android.builder.sdkDownload=false